In [18]:
import pandas as pd
import gzip
import json
import numpy as np
import pyarrow.parquet as pq
import altair as alt

# LabWork

In [ ]:
# file_path_r = "../data/raw/Electronics.jsonl.gz"
# file_path_m = "../data/raw/meta_Electronics.jsonl.gz"

# n_rows = 2000

# reviews = []

# with gzip.open(file_path_r, "rt") as f:

#     for i, line in enumerate(f):
#         if i >= n_rows:
#             break
#         reviews.append(json.loads(line))

# meta = []
# with gzip.open(file_path_m, "rt") as f:

#     for i, line in enumerate(f):
#         if i >= n_rows:
#             break
#         meta.append(json.loads(line))


# review_df = pd.DataFrame(reviews)
# meta = pd.DataFrame(meta)

In [ ]:
# review_df.head()
# KEY: parent_asin
# core: title (descriptor), helpful_vote,
# nice to have: rating, text (cluttered/explode)
# no:  images, asin, user_id, timestamp, verified_purchase(not for query view), helpful_vote

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3.0,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1658185117948,0,True
1,1.0,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1592678549731,0,True
2,5.0,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093017534,0,True
3,5.0,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,1290278495000,18,True
4,5.0,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,1676601581238,0,True

In [ ]:
# meta.head(10)
# KEY: parent_asin
# at min: main_category, title, features, description, details
# nice to haves: rating_number, average_rating, price, store 
# no: images, videos, subtitle, author, bought_together(empty)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fat Shark,"[Electronics, Television & Video, Video Glasses]","{'Date First Available': 'August 2, 2014', 'Ma...",B00MCW7G9M,None,NaN,NaN
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],SIIG,"[Electronics, Television & Video, Accessories,...",{'Product Dimensions': '0.83 x 4.17 x 2.05 inc...,B00YT6XQSE,None,NaN,NaN
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'AL 2Sides Video', 'url': 'https://...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","{'Brand': 'Digi-Tatoo', 'Color': 'Fresh Marble...",B07SM135LS,None,NaN,NaN
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","{'Date First Available': 'May 29, 2020', 'Manu...",B089CNGZCW,None,NaN,NaN
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Verizon,"[Electronics, Computers & Accessories, Compute...",{'Product Dimensions': '11.6 x 6.9 x 3.1 inche...,B004E2Z88O,None,NaN,NaN
5,Sports & Outdoors,Raymarine Wi-Fish DownVision Blackbox Sonar wi...,3.5,25,[Black box Wi-Fi CHIRP DownVision sonar module...,[Transform your smartphone into a powerful CHI...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Raymarine,"[Electronics, Car & Vehicle Electronics, Marin...",{'Item Package Dimensions L x W x H': '9.3 x 8...,B00TX536EK,None,NaN,NaN
6,Cell Phones & Accessories,"QGHXO Band for Garmin Vivofit 4, Soft Silicone...",4.4,707,[Personalized Your Garmin Vivofit 4 Activity T...,"[Compatibility, Custom designed for your preci...",14.89,[{'thumb': 'https://m.media-amazon.com/images/...,[],QGHXO,"[Electronics, Wearable Technology, Arm & Wrist...",{'Package Dimensions': '6.85 x 4.37 x 1.1 inch...,B07BJ7ZZL7,None,NaN,NaN
7,Industrial & Scientific,Protech iPhone 4 microscope 60X Lens with illu...,3.8,6,[iPhone 4 Microscope with White 2-LED and Dete...,[This accessory will convert your iPhone 4 int...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],ProTech,"[Electronics, Camera & Photo, Binoculars & Sco...","{'Light Source Type': 'LED', 'Color': 'Blue,Wh...",B005G99O2U,None,NaN,NaN
8,Computers,MOSISO Plastic Hard Shell Case & Keyboard Cove...,5.0,2,[],[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],MOSISO,"[Electronics, Headphones, Earbuds & Accessorie...","{'Brand': 'MOSISO', 'Item Weight': '8 ounces',...",B01MCZP7RF,None,NaN,NaN
9,None,"Fishfinder, Depth Finder Poly Sun Cover for 3""...",4.4,86,"[Made of poly material, Available in black, Dr...",[Affordable and convenient way to cover your s...,10.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Unboxing Gamin Vivid ', 'url': 'ht...",Westlake Market,"[Electronics, Car & Vehicle Electronics, Marin...",{'Item Package Dimensions L x W x H': '7.32 x ...,B00R6R82HS,None,NaN,NaN

In [ ]:
# meta = meta.replace({None: np.nan})
# meta["bought_together"]
# meta[meta["bought_together"].notnull()]

Empty DataFrame
Columns: [main_category, title, average_rating, rating_number, features, description, price, images, videos, store, categories, details, parent_asin, bought_together, subtitle, author]
Index: []

In [ ]:
# meta["bought_together"].unique()

array([nan])

In [ ]:
# hard_drop = ["images", "videos", "subtitle", "author", "bought_together"]
# nice_but_drop = ["rating_number", "average_rating", "price", "store"]
# full_drop = hard_drop + nice_but_drop
# meta_subset = meta.drop(columns= full_drop)

In [ ]:
# meta_subset.to_csv("../data/processed/meta_subset.csv",index=False)

# EDA

In [19]:
# Reading parquet files
table = pq.read_table("../data/processed/merged_subset.parquet")
merged_df = table.to_pandas()

table = pq.read_table("../data/processed/meta_raw_subset.parquet")
meta_df = table.to_pandas()

table = pq.read_table("../data/processed/reviews_raw_subset.parquet")
reviews_df = table.to_pandas()

In [12]:
# Examine the merged dataframe and its columns
merged_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 177698 entries, 0 to 177697
Data columns (total 8 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   parent_asin    177698 non-null  str
 1   main_category  171798 non-null  str
 2   title          177698 non-null  str
 3   features       177698 non-null  object
 4   description    177698 non-null  object
 5   details        177698 non-null  object
 6   title_1        177698 non-null  str
 7   helpful_vote   177698 non-null  int64
dtypes: int64(1), object(3), str(4)
memory usage: 10.8+ MB

In [15]:
# Example records of the merged dataframe
merged_df.head()

,parent_asin,main_category,title,features,description,details,title_1,helpful_vote
0,B071J3PFJJ,Computers,"ProCase iPad Air (3rd Gen) 10.5"" 2019 / iPad P...",[Designed exclusively for Apple iPad Air (3rd ...,[],"[(Standing screen display size, ""10.5 Inches"")...",Decent case,0
1,B00FEY28HA,Camera & Photo,Camera Case - Evecase Digital SLR/DSLR Profess...,[Evecase high quality nylon case easy to remov...,[],"[(Product Dimensions, ""6.69 x 7.87 x 5.51 inch...","Color is as description states, RED",0
2,B09NVYBTCF,Home Audio & Theater,MP3 Player 32GB with Speaker Earphone Portable...,[🎼 【Upgraded Shuffle Feature】Support random pl...,[],"[(Package Dimensions, ""5.67 x 3.15 x 0.79 inch...",Works,2
3,B0798MV7NS,Camera & Photo,REOLINK Solar Panel Power Supply Designed for ...,[],[],"[(Brand, ""REOLINK""), (Material, ""Monocrystalli...",Works good with Reolink cameras,0
4,B07H25G6FN,NaN,"eufy Security Floodlight Camera, 1080p, No Mon...",[Time to Upgrade Your Floodlights: Enhance you...,[],"[(Product Dimensions, ""7.09 x 7.87 x 12.2 inch...",It don’t work,0

In [13]:
# Examine the meta dataframe and its columns
meta_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    494 non-null    str
 1   title            500 non-null    str
 2   average_rating   500 non-null    float64
 3   rating_number    500 non-null    int64
 4   features         500 non-null    object
 5   description      500 non-null    object
 6   price            227 non-null    float64
 7   images           500 non-null    object
 8   videos           500 non-null    object
 9   store            498 non-null    str
 10  categories       500 non-null    object
 11  details          500 non-null    object
 12  parent_asin      500 non-null    str
 13  bought_together  0 non-null      object
 14  subtitle         0 non-null      str
 15  author           0 non-null      object
dtypes: float64(2), int64(1), object(8), str(5)
memory usage: 62.6+ KB

In [16]:
# Example records of the metadata dataframe
meta_df.head()

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,All Electronics,FS-1051 FATSHARK TELEPORTER V3 HEADSET,3.5,6,[],[Teleporter V3 The “Teleporter V3” kit sets a ...,NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],Fat Shark,"[Electronics, Television & Video, Video Glasses]","[(Date First Available, ""August 2, 2014""), (Ma...",B00MCW7G9M,None,NaN,None
1,All Electronics,Ce-H22B12-S1 4Kx2K Hdmi 4Port,5.0,1,"[UPC: 662774021904, Weight: 0.600 lbs]",[HDMI In - HDMI Out],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,[],SIIG,"[Electronics, Television & Video, Accessories,...","[(Product Dimensions, ""0.83 x 4.17 x 2.05 inch...",B00YT6XQSE,None,NaN,None
2,Computers,Digi-Tatoo Decal Skin Compatible With MacBook ...,4.5,246,[WARNING: Please IDENTIFY MODEL NUMBER on the ...,[],19.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'AL 2Sides Video', 'url': 'https://...",Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...","[(Brand, ""Digi-Tatoo""), (Color, ""Fresh Marble""...",B07SM135LS,None,NaN,None
3,AMAZON FASHION,NotoCity Compatible with Vivoactive 4 band 22m...,4.5,233,[☛NotoCity 22mm band is designed for Vivoactiv...,[],9.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...","[(Date First Available, ""May 29, 2020""), (Manu...",B089CNGZCW,None,NaN,None
4,Cell Phones & Accessories,Motorola Droid X Essentials Combo Pack,3.8,64,"[New Droid X Essentials Combo Pack, Exclusive ...",[all Genuine High Quality Motorola Made Access...,14.99,[{'thumb': 'https://m.media-amazon.com/images/...,[],Verizon,"[Electronics, Computers & Accessories, Compute...","[(Product Dimensions, ""11.6 x 6.9 x 3.1 inches...",B004E2Z88O,None,NaN,None

In [14]:
# Examine the reviews dataframe and its columns
reviews_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             500 non-null    float64
 1   title              500 non-null    str
 2   text               500 non-null    str
 3   images             500 non-null    object
 4   asin               500 non-null    str
 5   parent_asin        500 non-null    str
 6   user_id            500 non-null    str
 7   timestamp          500 non-null    int64
 8   helpful_vote       500 non-null    int64
 9   verified_purchase  500 non-null    bool
dtypes: bool(1), float64(1), int64(2), object(1), str(5)
memory usage: 35.8+ KB

In [17]:
# Example records of the reviews dataframe
reviews_df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,3.0,Smells like gasoline! Going back!,First & most offensive: they reek of gasoline ...,[{'small_image_url': 'https://m.media-amazon.c...,B083NRGZMM,B083NRGZMM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1658185117948,0,True
1,1.0,Didn’t work at all lenses loose/broken.,These didn’t work. Idk if they were damaged in...,[],B07N69T6TM,B07N69T6TM,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1592678549731,0,True
2,5.0,Excellent!,I love these. They even come with a carry case...,[],B01G8JO5F2,B01G8JO5F2,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1523093017534,0,True
3,5.0,Great laptop backpack!,I was searching for a sturdy backpack for scho...,[],B001OC5JKY,B001OC5JKY,AGGZ357AO26RQZVRLGU4D4N52DZQ,1290278495000,18,True
4,5.0,Best Headphones in the Fifties price range!,I've bought these headphones three times becau...,[],B013J7WUGC,B07CJYMRWM,AG2L7H23R5LLKDKLBEF2Q3L2MVDA,1676601581238,0,True

In [23]:
# EDA plot 1: Distribution of main_category
chart = alt.Chart(meta_df).mark_bar().encode(
    x=alt.X('count():Q', title='Count'),
    y=alt.Y('main_category:N', sort='-x', title='Category'),
    tooltip=['main_category', 'count()']
).properties(
    title='Distribution of Main Categories',
    width=600,
    height=400
)

chart

alt.Chart(...)

In [24]:
# EDA plot 2: Distribution of ratings
chart = alt.Chart(reviews_df).mark_bar().encode(
    x=alt.X('count():Q', title='Count'),
    y=alt.Y('rating:N', sort='-x', title='Rating'),
    tooltip=['rating', 'count()']
).properties(
    title='Distribution of Review Ratings',
    width=600,
    height=400
)

chart

alt.Chart(...)

## Selection and justification of fields for retrieval

For the metadata table, we decided to select main_category, title, features, description and details as the fields we would include for retrieval. We chose these columns because each one adds a unique identifier to many of the devices in our category. The labels in main_category are often used in user queries if they aren't sure what they are looking for, or they are searching by function instead of by product. The title field narrows the search down a bit in case the user wants to search for a specific line of products, such as iPad or Security Camera with Flood Light. The remaining columns (features, description and details) all add more granular data to the document for each product if the user query includes specifics down to the specifications or a particular model of the device.

For the reviews table, we only included title and helpful_vote as required columns. We wanted to avoid adding the entire review because that would make the document too large to compute without adding too much valuable information. To avoid adding the entire review, we believe the title field will provide a good summary of the review's contents. The helpful_vote field was also included because we may have future plans to expand our retrieval system to consider the number of helpful votes of a recommended product, with the assumption that reviews with more helpful votes should have more weight in how good a product is. However, this feature may be out of scope for this milestone.

## Description of Test Preprocessing Decisions

To start, the usual text preprocessing will be done, which will include removing stopwords, punctuation and whitespace before tokenizing the documents to build the corpus. For more specific columns, we have cleaned the input to maximize the amount of useful information and reduce noise. For example, we are only taking the first 100 characters of the title column in the metadata table because otherwise there would be a lot of noise in some of the product titles. We will also perform preprocessing on the features, description and details columns in the metadta table to flatten them into 1 string.